apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: vndvldpvs-go-gitops
  description: This is GitOps manifest for vndvldpvs-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=vndvldpvs-go
    backstage.io/kubernetes-id: vndvldpvs-go 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: rhtap-qe-jsmid/vndvldpvs-go-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:vndvldpvs-go
